import type { LocalResource, Workshop, LocalMeetup } from '@/types';

export const LOCAL_RESOURCES: LocalResource[] = [
  // ── United States ──────────────────────────────────────────────────────────
  {
    id: 'us-lgbtq-1',
    name: 'The Trevor Project',
    type: 'lgbtq_center',
    description: 'Crisis intervention and suicide prevention for LGBTQ+ youth under 25.',
    country: 'United States',
    website: 'https://www.thetrevorproject.org',
    phone: '1-866-488-7386',
  },
  {
    id: 'us-lgbtq-2',
    name: 'PFLAG National',
    type: 'support_group',
    description: 'Family, ally, and LGBTQ+ support with chapters in every US state.',
    country: 'United States',
    website: 'https://pflag.org',
  },
  {
    id: 'us-shelter-1',
    name: 'Ali Forney Center',
    type: 'shelter',
    description: 'NYC-based shelter and services for homeless LGBTQ+ youth.',
    country: 'United States',
    city: 'New York',
    website: 'https://www.aliforneycenter.org',
    phone: '212-206-0574',
  },
  {
    id: 'us-therapist-1',
    name: 'Psychology Today — LGBTQ+ Therapist Finder',
    type: 'therapist',
    description: 'Directory of affirming therapists across the US.',
    country: 'United States',
    website: 'https://www.psychologytoday.com/us/therapists/lgbtq',
  },
  {
    id: 'us-legal-1',
    name: 'Lambda Legal',
    type: 'legal_aid',
    description: 'Legal defense and education for LGBTQ+ rights across the US.',
    country: 'United States',
    website: 'https://www.lambdalegal.org',
    phone: '212-809-8585',
  },
  {
    id: 'us-support-1',
    name: 'GLSEN',
    type: 'support_group',
    description: 'Supports LGBTQ+ students in K-12 schools; GSA network and resources.',
    country: 'United States',
    website: 'https://www.glsen.org',
  },

  // ── Brazil ─────────────────────────────────────────────────────────────────
  {
    id: 'br-lgbtq-1',
    name: 'ABGLT — Associação Brasileira de Lésbicas, Gays, Bissexuais, Travestis, Transexuais e Intersexos',
    type: 'lgbtq_center',
    description: 'Maior organização LGBT+ do Brasil. Referência em direitos humanos e políticas públicas.',
    country: 'Brazil',
    website: 'https://www.abglt.org',
    phone: '+55 61 3321-6969',
  },
  {
    id: 'br-lgbtq-2',
    name: 'Grupo Arco-Íris',
    type: 'lgbtq_center',
    description: 'Centro de cidadania LGBT+ no Rio de Janeiro com serviços de acolhimento e orientação jurídica.',
    country: 'Brazil',
    city: 'Rio de Janeiro',
    website: 'https://www.arco-iris.org.br',
  },
  {
    id: 'br-shelter-1',
    name: 'Casa 1 — Centro de Acolhimento LGBTI+',
    type: 'shelter',
    description: 'Casa de acolhimento para jovens LGBT+ em situação de vulnerabilidade em São Paulo.',
    country: 'Brazil',
    city: 'São Paulo',
    website: 'https://www.casaum.org',
    phone: '+55 11 3392-1786',
  },
  {
    id: 'br-therapist-1',
    name: 'CFP — Conselho Federal de Psicologia',
    type: 'therapist',
    description: 'Diretório de psicólogos com especialização em diversidade sexual e de gênero.',
    country: 'Brazil',
    website: 'https://cadastro.cfp.org.br',
  },
  {
    id: 'br-legal-1',
    name: 'Instituto Brasileiro Trans de Educação (IBTE)',
    type: 'legal_aid',
    description: 'Apoio jurídico e social para pessoas trans e travestis em todo o Brasil.',
    country: 'Brazil',
    website: 'https://ibte.org.br',
  },
  {
    id: 'br-support-1',
    name: 'Aliança Nacional LGBTI+',
    type: 'support_group',
    description: 'Rede de grupos de apoio para pessoas LGBT+ e familiares em diferentes estados.',
    country: 'Brazil',
    website: 'https://www.aliancalgbti.org.br',
  },

  // ── United Kingdom ─────────────────────────────────────────────────────────
  {
    id: 'gb-lgbtq-1',
    name: 'Stonewall UK',
    type: 'lgbtq_center',
    description: "Britain's largest LGBT+ rights charity with national advocacy and local support.",
    country: 'United Kingdom',
    website: 'https://www.stonewall.org.uk',
  },
  {
    id: 'gb-lgbtq-2',
    name: 'Albert Kennedy Trust',
    type: 'shelter',
    description: 'Provides housing and support for LGBTQ+ young people aged 16–25 who are homeless.',
    country: 'United Kingdom',
    website: 'https://www.akt.org.uk',
    phone: '0207 831 6562',
  },
  {
    id: 'gb-therapist-1',
    name: 'Pink Therapy',
    type: 'therapist',
    description: 'UK directory of LGBTQ+ affirmative therapists and counsellors.',
    country: 'United Kingdom',
    website: 'https://pinktherapy.com',
  },
  {
    id: 'gb-legal-1',
    name: 'Galop — LGBT+ Anti-Violence Charity',
    type: 'legal_aid',
    description: 'Legal advice and support for LGBT+ people experiencing abuse or hate crime.',
    country: 'United Kingdom',
    website: 'https://galop.org.uk',
    phone: '0800 999 5428',
  },
  {
    id: 'gb-support-1',
    name: 'MindOut LGBTQ+ Mental Health Service',
    type: 'support_group',
    description: 'Peer support groups and advocacy for LGBTQ+ people experiencing mental health issues.',
    country: 'United Kingdom',
    city: 'Brighton',
    website: 'https://mindout.org.uk',
    phone: '01273 234 839',
  },

  // ── Canada ─────────────────────────────────────────────────────────────────
  {
    id: 'ca-lgbtq-1',
    name: 'Egale Canada',
    type: 'lgbtq_center',
    description: "Canada's leading organization for LGBTQ2+ rights and inclusion.",
    country: 'Canada',
    website: 'https://egale.ca',
  },
  {
    id: 'ca-shelter-1',
    name: 'Sprott House — Covenant House Canada',
    type: 'shelter',
    description: 'LGBTQ+ affirming emergency shelter for youth in Toronto.',
    country: 'Canada',
    city: 'Toronto',
    website: 'https://www.covenanthousetoronto.ca',
    phone: '416-204-7057',
  },
  {
    id: 'ca-therapist-1',
    name: 'Therapy Online — LGBTQ+ Affirming',
    type: 'therapist',
    description: 'Online therapy matching for LGBTQ+ Canadians with affirming therapists.',
    country: 'Canada',
    website: 'https://www.therapyonline.ca',
  },
  {
    id: 'ca-legal-1',
    name: 'Egale Canada Legal Resources',
    type: 'legal_aid',
    description: 'Legal information for LGBTQ+ Canadians on rights, discrimination, and family law.',
    country: 'Canada',
    website: 'https://egale.ca/advocacy',
  },
  {
    id: 'ca-support-1',
    name: 'Trans Lifeline',
    type: 'support_group',
    description: 'Peer support hotline and community for trans and non-binary people.',
    country: 'Canada',
    website: 'https://translifeline.org/hotline',
    phone: '877-330-6366',
  },

  // ── Australia ──────────────────────────────────────────────────────────────
  {
    id: 'au-lgbtq-1',
    name: 'QLife Australia',
    type: 'lgbtq_center',
    description: 'National telephone and web counselling and referral for LGBTQ+ people.',
    country: 'Australia',
    website: 'https://qlife.org.au',
    phone: '1800 184 527',
  },
  {
    id: 'au-shelter-1',
    name: 'Twenty10 — LGBTQ+ Housing Support',
    type: 'shelter',
    description: 'Housing, counselling, and social support for LGBTQ+ young people in NSW.',
    country: 'Australia',
    city: 'Sydney',
    website: 'https://twenty10.org.au',
    phone: '02 9360 2555',
  },
  {
    id: 'au-therapist-1',
    name: 'Australian Psychological Society — LGBTQ+ Finder',
    type: 'therapist',
    description: 'Directory of affirming psychologists across Australia.',
    country: 'Australia',
    website: 'https://www.psychology.org.au/Find-a-Psychologist',
  },
  {
    id: 'au-legal-1',
    name: 'LGBTQ+ Legal Service (QLD)',
    type: 'legal_aid',
    description: 'Free legal advice for LGBTQ+ people in Queensland on discrimination and family matters.',
    country: 'Australia',
    website: 'https://lgbtqlegalservice.org.au',
    phone: '07 3392 0184',
  },
  {
    id: 'au-support-1',
    name: 'PFLAG Australia',
    type: 'support_group',
    description: 'Family and ally support groups for LGBTQ+ people across Australia.',
    country: 'Australia',
    website: 'https://www.pflag.org.au',
  },

  // ── Germany ────────────────────────────────────────────────────────────────
  {
    id: 'de-lgbtq-1',
    name: 'LSVD — Lesben- und Schwulenverband',
    type: 'lgbtq_center',
    description: 'Deutschlands größter LGBT+-Verband mit Beratung, Rechtshilfe und Community-Angeboten.',
    country: 'Germany',
    website: 'https://www.lsvd.de',
    phone: '+49 221 925 96 10',
  },
  {
    id: 'de-shelter-1',
    name: 'Coming Out Haus Berlin',
    type: 'shelter',
    description: 'Notunterkunft und Beratungszentrum für LGBTQ+-Jugendliche in Berlin.',
    country: 'Germany',
    city: 'Berlin',
    website: 'https://schwulenberatungberlin.de',
    phone: '+49 30 233 691 0',
  },
  {
    id: 'de-therapist-1',
    name: 'Beratungsstelle Lebensberatung — LSVD',
    type: 'therapist',
    description: 'Psychologische Beratung für LGBT+ Menschen, auch online verfügbar.',
    country: 'Germany',
    website: 'https://www.lsvd.de/de/beratung',
  },
  {
    id: 'de-legal-1',
    name: 'LSVD Rechtshilfe',
    type: 'legal_aid',
    description: 'Kostenlose Rechtsberatung zu Diskriminierung, Partnerschaft und Asyl für LGBT+.',
    country: 'Germany',
    website: 'https://www.lsvd.de/de/recht',
  },
];

export const WORKSHOPS: Workshop[] = [
  {
    id: 'ws-1',
    title: 'Coming Out with Confidence',
    description: 'A gentle 4-week online workshop helping you prepare your story and practice conversations at your own pace.',
    host: 'HomeWithin Community',
    format: 'online',
    recurring: 'Monthly — first Sunday',
    category: 'coming_out',
    free: true,
    link: 'https://homewithin.app/workshops/coming-out',
  },
  {
    id: 'ws-2',
    title: 'Healing from Family Rejection',
    description: 'Facilitated peer support sessions for those navigating distance or rejection from family of origin.',
    host: 'HomeWithin Community',
    format: 'online',
    recurring: 'Bi-weekly — Saturdays 18:00 UTC',
    category: 'family_rejection',
    free: true,
    link: 'https://homewithin.app/workshops/family-healing',
  },
  {
    id: 'ws-3',
    title: 'Building Your Chosen Family',
    description: 'Interactive workshop on identifying, nurturing, and growing your network of chosen support.',
    host: 'HomeWithin Community',
    format: 'online',
    recurring: 'Monthly — third Saturday',
    category: 'chosen_family',
    free: true,
    link: 'https://homewithin.app/workshops/chosen-family',
  },
  {
    id: 'ws-4',
    title: 'Mindfulness for LGBTQ+ Wellbeing',
    description: 'Weekly guided mindfulness practice tailored to queer experiences of stress and hypervigilance.',
    host: 'HomeWithin Community',
    format: 'online',
    recurring: 'Weekly — Wednesdays 19:00 UTC',
    category: 'mental_health',
    free: true,
    link: 'https://homewithin.app/workshops/mindfulness',
  },
  {
    id: 'ws-5',
    title: 'Trans+ Peer Café',
    description: 'Informal drop-in space for trans, non-binary, and gender-questioning people to connect and share.',
    host: 'HomeWithin Community',
    format: 'online',
    recurring: 'Weekly — Fridays 20:00 UTC',
    category: 'trans_support',
    free: true,
    link: 'https://homewithin.app/workshops/trans-cafe',
  },
  {
    id: 'ws-6',
    title: 'Queer Grief & Loss Circle',
    description: 'A gentle space to process grief — from relationships, family estrangement, or identity losses.',
    host: 'HomeWithin Community',
    format: 'online',
    recurring: 'Monthly — last Thursday',
    category: 'grief',
    free: true,
    link: 'https://homewithin.app/workshops/grief-circle',
  },
];

export const LOCAL_MEETUPS: LocalMeetup[] = [
  {
    id: 'mt-us-1',
    title: 'NYC Queer Social',
    description: 'Casual monthly mixer for LGBTQ+ people of all backgrounds in Manhattan.',
    city: 'New York',
    country: 'United States',
    recurring: 'Monthly — first Friday',
    link: 'https://www.meetup.com/nyc-lgbtq',
  },
  {
    id: 'mt-us-2',
    title: 'LA Pride Walking Group',
    description: 'Sunday morning walks through LA parks — all fitness levels welcome.',
    city: 'Los Angeles',
    country: 'United States',
    recurring: 'Weekly — Sundays 8am',
    link: 'https://www.meetup.com/la-pride-walk',
  },
  {
    id: 'mt-br-1',
    title: 'Grupo de Apoio LGBTQ+ São Paulo',
    description: 'Encontros quinzenais de acolhimento e troca de experiências na capital paulistana.',
    city: 'São Paulo',
    country: 'Brazil',
    recurring: 'Quinzenal — sábados às 15h',
    link: 'https://www.meetup.com/lgbtq-sp',
  },
  {
    id: 'mt-br-2',
    title: 'Roda de Conversa Trans — Rio',
    description: 'Espaço seguro para pessoas trans e não-binárias no Rio de Janeiro.',
    city: 'Rio de Janeiro',
    country: 'Brazil',
    recurring: 'Mensal — primeira quarta',
  },
  {
    id: 'mt-gb-1',
    title: 'London LGBTQ+ Coffee Mornings',
    description: 'Relaxed coffee meetups for LGBTQ+ people across London boroughs.',
    city: 'London',
    country: 'United Kingdom',
    recurring: 'Weekly — Saturdays 10am',
    link: 'https://www.meetup.com/london-lgbtq-coffee',
  },
  {
    id: 'mt-ca-1',
    title: 'Toronto Queer Hike',
    description: 'Accessible nature walks for LGBTQ+ people and allies in and around Toronto.',
    city: 'Toronto',
    country: 'Canada',
    recurring: 'Monthly — second Sunday',
    link: 'https://www.meetup.com/toronto-queer-hike',
  },
  {
    id: 'mt-au-1',
    title: 'Sydney LGBTQ+ Board Games Night',
    description: 'Low-key fortnightly board game sessions — great for meeting new queer friends.',
    city: 'Sydney',
    country: 'Australia',
    recurring: 'Bi-weekly — Thursdays 7pm',
    link: 'https://www.meetup.com/sydney-lgbtq-games',
  },
  {
    id: 'mt-de-1',
    title: 'Queeres Café Berlin',
    description: 'Offener Treff für LGBTQ+-Menschen in Berlin-Mitte — kein Eintritt, keine Agenda.',
    city: 'Berlin',
    country: 'Germany',
    recurring: 'Wöchentlich — Dienstags 18 Uhr',
  },
];

export const SUPPORTED_COUNTRIES = [
  'United States',
  'Brazil',
  'United Kingdom',
  'Canada',
  'Australia',
  'Germany',
] as const;
